### ISSUE TITLE
1像素的执着

### ISSUE THREAD

**Issue by phoebeCodeSpace** [wangyifen/blog#7]
> 记录处理兼容问题中遇到的css问题，它可能只是1px的偏差。

1.  Safari 浏览器 二次访问 a标签内border颜色变成深蓝色
```
//处理办法：border改为内置阴影
border-bottom: 1px solid  #E8E8E8;
 =>
box-shadow:inset 0px -1px 0 #E8E8E8;
```	
2. 滚动不流畅问题
```
overflow-scrolling: touch;
-webkit-overflow-scrolling: touch;
```

3. 优化transform在过渡效果中出现文字模糊和抖动问题
① 将元素的宽、高度设置为偶数
② 改成`transform: translate(-50%, -52%)`（如果52%不行则从51%每个百分比尝试）

4. css改变输入框光标颜色

``` css
input,textarea{
   caret-color: red;
}
input,textarea { 
    color: rgb(60, 0, 248); /* 光标的颜色*/ 
    color\0: #333;   /* IE hack*/ 
   -webkit-text-fill-color: #333;  /* 文本颜色 */ 
}
```

5. 实现半像素边框

① 目标元素相对定位
② 伪元素绝对定位
③ 伪元素1px宽
④ 伪元素宽高设置为2倍
⑤ 伪元素缩小0.5倍
⑥ 把border包进来（否则边框不会一起缩放）

```css
.thinner-border {
    position: relative;
}

.thinner-border:before {
    content: '';
    position: absolute;
    width: 200%;
    height: 200%;
    border: 1px solid #000;
    transform-origin: 0 0;
    transform: scale(0.5, 0.5);
    box-sizing: border-box;
}
```
